## Problem 1: Visualise data in a static map (10 points)


Create a *static* **thematic map** using the skills you learnt during lesson 5. The map should <br>
contain more than one layer (from at least two different data sets). Pay attention to classification <br>
and visualisation (appropriate colour scheme choice, etc.). Write your code in this notebook, and <br>
store the resulting maps in `.png` format in the `NOTEBOOK_DIRECTORY / "docs"` folder.

### Topic of the map

- Use any of the data sets we have used during the course (travel time data, population grid), or <br>
  any other data set of your interest (for example, [open data sets from Statistics Finland](https://www.stat.fi/org/avoindata/index_en.html), <br>
  or the open geo-data from [the Helsinki Region Infoshare](https://hri.fi/en)). If you download <br>
  data sets, add, commit, and push them to the `DATA_DIRECTORY`. Be sure to include an attribution <br>
  to each data set in your output map!
- Feel free to start from and adapt examples from the course material! You can take one step further <br>
  and add additional analysis to, e.g., the shopping centre dominance or the population within vincinity <br>
  of certain addresses)

### Criteria

- The map has more than one data layer (for instance, the results of an analysis, and the road network <br>
  to illustrate a complex spatial pattern). If (and only if) you think it adds additional value, feel <br>
  free to add a base map (but a base map does not count as an own layer) (2 points)
- The map portrays the output of an analysis or a classification that adds value beyond just displaying <br>
  the raw data (3 points)
- The map follows good cartographic practices (appropriate map extent and zoom level, colour scheme, <br>
  legend and data sources, etc.) (5 points)

### Output

- Save the map(s) in `.png` format in the `NOTEBOOK_DIRECTORY / "docs"` folder, remember to add, commit, <br>
  and push them to the GitHub repository
- Remember to also add, commit, and push input data sets and code

---

In [26]:
import pathlib 
NOTEBOOK_PATH = pathlib.Path().resolve()
DATA_DIRECTORY = NOTEBOOK_PATH / "data"
OUTPUT_DIRECTORY = NOTEBOOK_PATH / "docs"

In [2]:
# ADD YOUR OWN CODE HERE

In [27]:
import geopandas
WFS_BASE_URL = (
    "https://geo.stat.fi/geoserver/ows"
    "?service=wfs"
    "&version=2.0.0"
    "&request=GetFeature"
    "&srsName=EPSG:3067"
    "&typeName={layer:s}"
)
schools = (
    geopandas.read_file(
        WFS_BASE_URL.format(layer="oppilaitokset")
    )
    .set_crs("EPSG: 3067")
)
schools.head()
#schools = schools[["oltyp_nimi","onimi", "euref_x", "euref_y","geometry"]]
#schools.head()

,gml_id,id,oltyp_nimi,til_vuosi,tunn,onimi,olo,oltyp,euref_x,euref_y,geometry
0,oppilaitokset.1,1,Peruskoulut,2025,08888,Tusby träsk svenska skola,0,11,392861.0,6699246.0,POINT (392861 6699246)
1,oppilaitokset.2,2,Peruskoulut,2025,08871,Aapiskujan koulu,0,11,340457.0,7007582.0,POINT (340457 7007582)
2,oppilaitokset.3,3,Peruskoulut,2025,03117,Aarnivalkean koulu,0,11,378352.0,6673736.0,POINT (378352 6673736)
3,oppilaitokset.4,4,Peruskouluasteen erityiskoulut,2025,03874,Aavan koulu,0,12,372932.0,6756820.0,POINT (372932 6756820)
4,oppilaitokset.5,5,Peruskoulut,2025,03584,Ahjon koulu,0,11,397554.0,6697333.0,POINT (397554 6697333)

In [28]:
grid = (
    geopandas.read_file(
        WFS_BASE_URL.format(layer="vaestoruutu:vaki2025_5km")
    )
    .set_crs("EPSG: 3067")
)
municipalities = (
    geopandas.read_file(
        WFS_BASE_URL.format(layer="kunta1000k_2016")
    )
    .set_crs("EPSG: 3067")
)
municipalities.head()

,gml_id,gid,vuosi,kunta,nimi,namn,name,geometry
0,kunta1000k_2016.1,1,2016.0,005,Alajärvi,Alajärvi,Alajärvi,"MULTIPOLYGON (((347302.684 6959056.438, 346754..."
1,kunta1000k_2016.2,2,2016.0,009,Alavieska,Alavieska,Alavieska,"MULTIPOLYGON (((370424.741 7104339.038, 370110..."
2,kunta1000k_2016.3,3,2016.0,010,Alavus,Alavus,Alavus,"MULTIPOLYGON (((319892.311 6920033.249, 317757..."
3,kunta1000k_2016.4,4,2016.0,016,Asikkala,Asikkala,Asikkala,"MULTIPOLYGON (((434407.88 6774122.311, 434003...."
4,kunta1000k_2016.5,5,2016.0,018,Askola,Askola,Askola,"MULTIPOLYGON (((423421.791 6704555.878, 422418..."

In [29]:
# Crop schools and grid to cover only Turku
turku = municipalities[municipalities.name == "Turku"].copy()
turku

,gml_id,gid,vuosi,kunta,nimi,namn,name,geometry
280,kunta1000k_2016.280,280,2016.0,853,Turku,Åbo,Turku,"MULTIPOLYGON (((240357.887 6705903.86, 240360...."

In [32]:
turku_schools = schools[schools.within(turku.at[280,"geometry"])
    ]
turku_schools

,gml_id,id,oltyp_nimi,til_vuosi,tunn,onimi,olo,oltyp,euref_x,euref_y,geometry
79,oppilaitokset.80,80,Peruskoulut,2025,08548,Aunelan koulu,0,11,236163.00000,6.711922e+06,POINT (236163 6711922)
111,oppilaitokset.112,112,Peruskoulut,2025,08808,Cygnaeus skola,0,11,239598.00000,6.711255e+06,POINT (239598 6711255)
211,oppilaitokset.212,212,Peruskoulut,2025,03760,Haarlan koulu,0,11,236611.00000,6.704848e+06,POINT (236611 6704848)
246,oppilaitokset.247,247,Peruskoulut,2025,08549,Hannunniitun koulu,0,11,242972.00000,6.711487e+06,POINT (242972 6711487)
303,oppilaitokset.304,304,Peruskoulut,2025,08550,Hepokullan koulu,0,11,238854.00000,6.713900e+06,POINT (238854 6713900)
421,oppilaitokset.422,422,Peruskoulut,2025,08552,Ilpoisten koulu,0,11,240438.00000,6.707989e+06,POINT (240438 6707989)
521,oppilaitokset.522,522,Peruskoulut,2025,08553,Jäkärlän koulu,0,11,240994.00000,6.713973e+06,POINT (240994 6713973)
656,oppilaitokset.657,657,Peruskouluasteen erityiskoulut,2025,08580,Katariinan koulu,0,12,241410.00000,6.712002e+06,POINT (241410 6712002)
658,oppilaitokset.659,659,Lukiot,2025,00775,Katedralskolan i Åbo,0,15,240180.00000,6.710941e+06,POINT (240180 6710941)
711,oppilaitokset.711,711,Lukiot,2025,00008,Kerttulin lukio,0,15,240628.00000,6.710779e+06,POINT (240628 6710779)
748,oppilaitokset.748,748,Peruskouluasteen erityiskoulut,2025,03313,Kiinamyllyn koulu,0,12,241269.00000,6.710609e+06,POINT (241269 6710609)
941,oppilaitokset.941,941,Peruskoulut,2025,03364,Kuitinmäen koulu,0,11,243354.00000,6.708073e+06,POINT (243354 6708073)
1106,oppilaitokset.1106,1106,Peruskoulut,2025,08559,Lausteen koulu,0,11,244708.00000,6.708507e+06,POINT (244708 6708507)
1196,oppilaitokset.1197,1197,Peruskoulut,2025,08560,Luolavuoren koulu,0,11,241211.00000,6.708557e+06,POINT (241211 6708557)
1201,oppilaitokset.1202,1202,Lukiot,2025,00838,Luostarivuoren Lyseon lukio,0,15,239871.00000,6.710362e+06,POINT (239871 6710362)
1202,oppilaitokset.1203,1203,Peruskoulut,2025,08541,Luostarivuoren koulu,0,11,239871.00000,6.710362e+06,POINT (239871 6710362)
1319,oppilaitokset.1320,1320,Peruskouluasteen erityiskoulut,2025,08581,Mikaelin koulu,0,12,238990.00000,6.710649e+06,POINT (238990 6710649)
1361,oppilaitokset.1362,1362,Peruskouluasteen erityiskoulut,2025,03688,Mylly-Antin koulu,0,12,240450.00000,6.715639e+06,POINT (240450 6715639)
1469,oppilaitokset.1470,1470,Peruskoulut,2025,03310,Nummenpakan koulu,0,11,241497.00000,6.712112e+06,POINT (241497 6712112)
1551,oppilaitokset.1552,1552,Peruskoulut,2025,03797,Paattisten koulu,0,11,247069.00000,6.726209e+06,POINT (247069 6726209)
1576,oppilaitokset.1577,1577,Peruskoulut,2025,08566,Pansion koulu,0,11,234346.00000,6.711304e+06,POINT (234346 6711304)
1726,oppilaitokset.1727,1727,Peruskoulut,2025,08567,Puolalan koulu,0,11,239424.00000,6.711207e+06,POINT (239424 6711207)
1727,oppilaitokset.1728,1728,Lukiot,2025,00660,Puolalanmäen lukio,0,15,239620.00000,6.711202e+06,POINT (239620 6711202)
1733,oppilaitokset.1734,1734,Peruskoulut,2025,08545,Puropellon koulu,0,11,239950.00000,6.709886e+06,POINT (239950 6709886)
1764,oppilaitokset.1765,1765,Peruskoulut,2025,08568,Pääskyvuoren koulu,0,11,243495.00000,6.709983e+06,POINT (243495 6709983)
1795,oppilaitokset.1796,1796,Peruskoulut,2025,03140,Rastaalan koulu,0,11,240322.00000,6.710046e+06,POINT (240322 6710046)
1804,oppilaitokset.1805,1805,Peruskoulut,2025,08569,Raunistulan koulu,0,11,239864.00000,6.712366e+06,POINT (239864 6712366)
1826,oppilaitokset.1827,1827,Peruskoulut,2025,08546,Rieskalähteen koulu,0,11,239428.00000,6.712751e+06,POINT (239428 6712751)
1883,oppilaitokset.1884,1884,Peruskoulut,2025,08891,S:t Olofsskolan,0,11,239805.02168,6.710221e+06,POINT (239805.022 6710220.784)
1926,oppilaitokset.1927,1927,Peruskouluasteen erityiskoulut,2025,03314,Satulavuoren koulu,0,12,243070.00000,6.708913e+06,POINT (243070 6708913)
1981,oppilaitokset.1982,1982,Peruskoulut,2025,08809,Sirkkala skola,0,11,240516.00000,6.710443e+06,POINT (240516 6710443)
1982,oppilaitokset.1983,1983,Peruskouluasteen erityiskoulut,2025,08810,Sirkkalabackens skola,2,12,240516.00000,6.710443e+06,POINT (240516 6710443)
2072,oppilaitokset.2073,2073,Peruskoulut,2025,03866,Syvälahden koulu,0,11,237179.00000,6.707628e+06,POINT (237179 6707628)
2162,oppilaitokset.2163,2163,Peruskoulut,2025,08574,Teräsrautelan koulu,0,11,237931.00000,6.713286e+06,POINT (237931 6713286)
2197,oppilaitokset.2198,2198,Peruskoulut,2025,08538,Topeliuksen koulu,0,11,238090.00000,6.710020e+06,POINT (238090 6710020)
2229,oppilaitokset.2230,2230,Peruskoulut,2025,08542,Turun Lyseon koulu,0,11,240177.00000,6.715471e+06,POINT (240177 6715471)
2230,oppilaitokset.2231,2231,Perus- ja lukioasteen koulut,2025,03548,Turun Steiner-koulu,0,19,240930.00000,6.710817e+06,POINT (240930 6710817)
2231,oppilaitokset.2232,2232,Lukiot,2025,00837,Turun Suom. Yht.koulun lukio,0,15,239676.00000,6.711414e+06,POINT (239676 6711414)
2232,oppilaitokset.2233,2233,Lukiot,2025,00833,Turun iltalukio,0,15,239395.00000,6.710678e+06,POINT (239395 6710678)
2233,oppilaitokset.2234,2234,Perus- ja lukioasteen koulut,2025,03749,Turun kansainvälinen koulu,0,19,244754.00000,6.710232e+06,POINT (244754 6710232)
2234,oppilaitokset.2235,2235,Lukiot,2025,00834,Turun klassillinen lukio,0,15,239395.00000,6.710678e+06,POINT (239395 6710678)
2235,oppilaitokset.2236,2236,Perus- ja lukioasteen koulut,2025,00836,Turun normaalikoulu,0,19,244754.00000,6.710232e+06,POINT (244754 6710232)
2320,oppilaitokset.2321,2321,Peruskoulut,2025,03349,Varissuon koulu,6,11,244762.00000,6.710036e+06,POINT (244762 6710036)
2331,oppilaitokset.2332,2332,Peruskoulut,2025,08540,Vasaramäen koulu,0,11,241519.00000,6.709390e+06,POINT (241519 6709390)
2427,oppilaitokset.2428,2428,Peruskoulut,2025,08578,Vähä-Heikkilän koulu,0,11,238890.00000,6.709130e+06,POINT (238890 6709130)
2450,oppilaitokset.2451,2451,Peruskoulut,2025,08579,Wäinö Aaltosen koulu,0,11,237141.00000,6.706821e+06,POINT (237141 6706821)
2454,oppilaitokset.2455,2455,Peruskoulut,2025,08562,Yli-Maarian koulu,0,11,243444.00000,6.721010e+06,POINT (243444 6721010)